Send events for gcode scripts
OctoPrint/OctoPrint pull request #3903
Opened 2020-12-24 11:20 UTC by shadycuz

* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
This PR creates an event for each of the predefined GCODE scripts and any custom scripts the user might add. The main purpose of this PR was to allow people to do something when a print was complete. The problem is that currently, the last event to fire is `PrintDone` even if some "printing" was left in the `afterPrintDone` gcode. When implementing this fix/feature I thought it made sense to handle all predefined gcode and custom gcode. 

#### How was it tested? How can it be tested by the reviewer?
I tested this by sending a print to the virtual printer while running octoprint in debug.

```
2020-12-24 05:49:38,180 - octoprint.events.fire - DEBUG - Firing event: BeforePrintStartedGcodeRunning (Payload: {'name': 'test.gcode', 'path': 'test.gcode', 'origin': 'local', 'size': 56, 'owner': 'shadycuz', 'user': 'shadycuz'})
...
2020-12-24 05:49:38,195 - octoprint.events.fire - DEBUG - Firing event: BeforePrintStartedGcodeFinished (Payload: {'name': 'test.gcode', 'path': 'test.gcode', 'origin': 'local', 'size': 56, 'owner': 'shadycuz', 'user': 'shadycuz'})
...
2020-12-24 05:49:38,202 - octoprint.events.fire - DEBUG - Firing event: PrinterStateChanged (Payload: {'state_id': 'PRINTING', 'state_string': 'Printing'})
...
2020-12-24 05:49:38,210 - octoprint.events.fire - DEBUG - Firing event: PrinterStateChanged (Payload: {'state_id': 'FINISHING', 'state_string': 'Finishing'})
...
2020-12-24 05:49:38,220 - octoprint.events.fire - DEBUG - Firing event: PrintDone (Payload: {'name': 'test.gcode', 'path': 'test.gcode', 'origin': 'local', 'size': 56, 'owner': 'shadycuz', 'time': 0.03355369999917457})
...
2020-12-24 05:49:38,227 - octoprint.events.fire - DEBUG - Firing event: AfterPrintDoneGcodeRunning (Payload: {'name': 'test.gcode', 'path': 'test.gcode', 'origin': 'local', 'size': 56, 'owner': 'shadycuz', 'time': 0.03355369999917457})
...
2020-12-24 05:49:38,234 - octoprint.events.fire - DEBUG - Firing event: AfterPrintDoneGcodeFinished (Payload: {'name': 'test.gcode', 'path': 'test.gcode', 'origin': 'local', 'size': 56, 'owner': 'shadycuz', 'time': 0.03355369999917457})
```

#### Any background context you want to provide?

My specific use case is that users of [Octoprint-Twilio](https://github.com/taxilian/OctoPrint-Twilio) want to send themselves a picture after the print is complete. On some printers or specific print jobs, the gantry might be in between the finished print and the camera. With this PR merged users could add `afterPrintDone` GCODE to move the printer around in order to compose a nice shot for the camera. 

#### What are the relevant tickets if any?

Closes #3871 

#### Screenshots (if appropriate)

#### Further notes

I will be adding unit tests for the `Printer.script` method as soon as the implementation details are finalized. I will also change the docs soon to show an example of how I feel these new events could be displayed to users. 

My only concern is that the `script` method was very lean beforehand and now half of it is dedicated to handling the firing of events. I could move this logic to a function but I'm not sure where it would make sense? Would it be best as a static method? It's only 6 lines so maybe its not a big deal. 

I have a unit test failing but it seems something that is very specific to my setup. 

```
_________________________________________________________________________________________________________ TestSettings.test_set_external_modification _________________________________________________________________________________________________________

self = <settings.test_settings.TestSettings testMethod=test_set_external_modification>

    def test_set_external_modification(self):
        with self.mocked_config() as paths:
            basedir, configfile = paths
            settings = octoprint.settings.Settings()
    
            self.assertEqual("0.0.0.0", settings.get(["server", "host"]))
    
            # modify yaml file externally
            config = self._load_yaml(configfile)
            config["server"]["host"] = "127.0.0.1"
            self._dump_yaml(configfile, config)
    
            # set some value, should also reload file before setting new api key
            settings.set(["api", "key"], "key")
    
            # verify updated values
>           self.assertEqual("127.0.0.1", settings.get(["server", "host"]))
E           AssertionError: '127.0.0.1' != '0.0.0.0'
E           - 127.0.0.1
E           + 0.0.0.0
```

2020-12-24 17:17 UTC, cp2004 commented
> I have a unit test failing but it seems something that is very specific to my setup.

The tests on the PR seem to have run fine, not sure why that would fail in your setup but you seem to have an idea so I'll ignore that for now 🙂 

I wouldn't worry about the method having a few more calls in it, 6 lines is really not that much to worry about. It's not the kind of thing that would benefit from being extracted IMO. 

If you want to, you could use the builtin [`str.capitalize()`](https://docs.python.org/3/library/stdtypes.html#str.capitalize), to save on a bit of 'do-it-yourself' but the initial implementation looks OK to me.

Of course, I don't get final say, this is just the preliminary review round 😄

2020-12-26 17:05 UTC, shadycuz commented
@cp2004 

`'afterPrintDone'.capitalize()` == `Afterprintdone`

2020-12-26 17:22 UTC, cp2004 commented
Very good point 🤦‍♂️

2021-01-05 14:17 UTC, shadycuz commented on docs/events/index.rst
> +   .. versionadded:: X.X.X
This will need to be fixed when we know the version number.

2021-01-05 14:17 UTC, shadycuz commented on docs/features/gcode_scripts.rst
> +will be ``AfterPrintDoneFinished``. You can find more details in the :ref:`Events <sec-events-available_events-printing>` documentation.
I put the new events in the Printing section, but they would also fit well in the GCODE Processing section.

2021-01-18 10:52 UTC, foosel requested changes
I strongly welcome the idea! I have one concern though, and that is the current way to name the events. 

Instead of `${ScriptName}Running` and `${ScriptName}Finished` I think it would be better to make that `GcodeScript${ScriptName}Running` and `GcodeScript${ScriptName}Finished`. Prefix for clarity. 

I also noticed that you've documented `${ScriptName}Running` and `${ScriptName}Finished`, but the code currently generates `${ScriptName}GcodeRunning` and `${ScriptName}GcodeFinished`. Would get solved by the requested rename though.

Otherwise this looks good and ready to be merged! Version would be 1.6.0 btw.

2021-01-18 12:01 UTC, shadycuz commented
@foosel  good catch on the naming issue. Will change to your recommended name scheme and push something shortly.

I could also try adding some tests if you want? I see that `printer/standard.py` doesn't seem to have anything unless I missed it. I could create a test the checks if running a gcode script will fire the correct event.

2021-01-18 12:43 UTC, shadycuz commented
@foosel  It's actually becoming a lot of work to try and get a printer instance created to test. Can you think of a short cut haha? 

Here is where I have gotten so far...

```python
class ScriptsTestCase(unittest.TestCase):
    def setUp(self):

        slicingManager = SlicingManager(
            self._settings.getBaseFolder("slicingProfiles"), printerProfileManager
        )

        analysis_queue_factories = {
            "gcode": filemanager.analysis.GcodeAnalysisQueue
        }

        analysisQueue = filemanager.analysis.AnalysisQueue(
            analysis_queue_factories
        )

        fileManager = filemanager.FileManager(
            analysisQueue,
            slicingManager,
            printerProfileManager,
            initial_storage_managers=storage_managers,
        )

        self.printer = Printer()
```

I probably have another 5 things to import in and setup before I can create my printer instance.

2021-01-18 13:14 UTC, foosel commented
You should be able to use `mock` to mock all the injected dependencies, which would make this way less cumbersome. You'll also need to replace the `settings`, `plugin_manager` and `event_manager` factory methods with patched mocks.

``` python
import unittest
import mock

from octoprint.printer.standard import Printer

class ScriptsTestCase(unittest.TestCase):
    def setUp(self):
        # mock plugin manager
        self.plugin_manager = mock.MagicMock()
        self.plugin_manager.get_hooks.return_value = []
        self.plugin_manager.get_implementations = []

        self.plugin_manager_patcher = mock.patch("octoprint.plugin.plugin_manager")
        self.plugin_manager_getter = self.plugin_manager_patcher.start()
        self.plugin_manager_getter.return_value = self.plugin_manager

        # mock event manager
        self.event_manager = mock.MagicMock()

        self.event_manager_patcher = mock.patch("octoprint.events.event_manager")
        self.event_manager_getter = self.event_manager_patcher.start()
        self.event_manager_getter.return_value = self.event_manager

        # mock settings
        self.settings = mock.MagicMock()
        self.settings.getInt.return_value = 1;
        self.settings.getBoolean.return_value = False;

        self.settings_patcher = mock.patch("octoprint.settings.settings")
        self.settings_getter = self.settings_patcher.start()
        self.settings_getter.return_value = self.settings

        # mock injected dependencies
        fileManager = mock.MagicMock()
        analysisQueue = mock.MagicMock()
        printerProfileManager = mock.MagicMock()

        self.printer = Printer(fileManager, analysisQueue, printerProfileManager)
    
    def tearDown(self):
        self.plugin_manager_patcher.stop()
        self.event_manager_patcher.stop()
        self.settings_patcher.stop()
    
    # [...]
```

(untested though)

Testing whether the events get fired as expected would then boil down to checking if the call on the mocked `event_manager` has actually been made:

``` python
self.event_manager.assert_called_with("GcodeScriptAfterPrintDoneRunning", expected_payload)
```

I'd be fine with it however if you didn't want to jump through all of these hoops, considering that there isn't testing code yet that you can easily extend/copy.

2021-01-18 15:23 UTC, shadycuz commented
@foosel With your stater code I was able to get the tests working =). Please review again.

2021-01-18 15:30 UTC, shadycuz commented on tests/printer/test_script.py
> +        self.printer._comm = self.comm
In the future, all this setup could be refactored into a base test class for `Printer`.

2021-01-18 15:53 UTC, foosel approved these changes

2021-01-18 15:53 UTC, merged

2021-01-18 15:54 UTC, foosel commented
Looking good now! I rebased it against `maintenance` (it's an improvement of existing functionality, not a big huge new feature), it'll be part of 1.6.0.