📝 add instructions for setting up vscode IDE
OctoPrint/OctoPrint pull request #4190
Opened 2021-07-20 14:07 UTC by Sycha

* [ ] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [ ] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [ ] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [ ] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [ ] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
Adds vscode IDE setup instructions to the documentation, necessary as vscode is a popular IDE and therefore likely to be used by potential contributors.

#### How was it tested? How can it be tested by the reviewer?
Has been tested manually in an Ubuntu 20.04 VM. Install vscode and run through the instructions

#### Any background context you want to provide?

#### What are the relevant tickets if any?

#### Screenshots (if appropriate)

#### Further notes

2021-07-20 14:38 UTC, cp2004 requested changes
Very small (& picky) typos/word changes

2021-07-20 14:38 UTC, cp2004 commented on docs/development/environment.rst
> +    settings.json
Doesn't make sense here
```suggestion
```

2021-07-20 14:38 UTC, cp2004 commented on docs/development/environment.rst
> +  - Install Visual Studio from https://code.visualstudio.com/Download
```suggestion
  - Install Visual Studio Code from https://code.visualstudio.com/Download
```

2021-07-20 14:38 UTC, cp2004 commented on docs/development/environment.rst
> +                  "name": "Octoprint",
```suggestion
                  "name": "OctoPrint",
```
Very picky this one... 🙂

2021-07-20 14:38 UTC, cp2004 commented on docs/development/environment.rst
> +  * Your terminal inside vscode uses the virtrual python environment
```suggestion
  * Your terminal inside vscode uses the virtual python environment
```

2021-07-20 15:24 UTC, Sycha commented
Thanks @cp2004 for catching those typos. All good :+1: 

First time using github pull request review feature do let me know if I need to do something differently. Cheers

2021-07-20 16:30 UTC, foosel requested changes
Also found some minor issues (formatting primarily). Other than that it looks good :)

I'm wondering if there's a *built-in* option to use pre-commit for black, isort and flake8. As mentioned on Signal I currently use the Run on Save extension to do that, but of course that requires an additional extension whereas the currently documented approach here doesn't. 

Might make sense to maybe add black, isort and flake8 to the devel dependencies to get rid of one manual install step here if there's no built-in possibility?

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +  - Install Visual Studio Code from https://code.visualstudio.com/Download
Somehow the missing newline here irks me 😅

```suggestion

  - Install Visual Studio Code from `code.visualstudio.com <https://code.visualstudio.com/Download>`_
```

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +  - Create a directory '.vscode' if not already present in the root of the project
```suggestion
  - Create a directory ``.vscode`` if not already present in the root of the project
```

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +  - Create the following files inside the .vscode directory
```suggestion
  - Create the following files inside the ``.vscode`` directory
```

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +    .. code-block:: bash
Newline

```suggestion

    .. code-block:: bash
```

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +    .. code-block:: bash
Newline

```suggestion

    .. code-block:: bash
```

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +  * Pressing f5 will now start OctoPrint in debug
```suggestion
  * Pressing ``F5`` will now start OctoPrint in debug mode
```

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +  * Ctrl + shift + b can be used to run the 'build docs' task to rebuild the documentation
```suggestion
  * ``Ctrl+Shift+B`` can be used to run the ``build docs`` task to rebuild the documentation
```

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +        }
Something's not right with that indent...

```suggestion
      .. code-block:: json

         {
             "python.defaultInterpreterPath": "venv3/bin/python",
             "python.formatting.provider": "black",
             "python.formatting.blackArgs": [
                 "--config",
                 "black.toml"
             ],
             "editor.formatOnSave": true,
             "python.sortImports.args": [
                 "--profile=black",
             ],
             "[python]": {
                 "editor.codeActionsOnSave": {
                     "source.organizeImports": true
                 }
             },
             "python.linting.pylintEnabled": false,
             "python.linting.flake8Enabled": true,
             "python.linting.enabled": true
         }
```

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +        }
Indent

```suggestion
      .. code-block:: json

         {
           "version": "2.0.0",
           "tasks": [
             {
                 "label": "clean build artifacts",
                 "type": "shell",
                 "command": "python ./setup.py clean"
             },
             {
                 "label": "build docs",
                 "type": "shell",
                 "command": "sphinx-build -b html ./docs ./docs/_build"
             }
           ]
         }
```

2021-07-20 16:30 UTC, foosel commented on docs/development/environment.rst
> +        }
Indent

```suggestion
      .. code-block:: json

         {
           "version": "0.2.0",
           "configurations": [
               {
                   "name": "OctoPrint",
                   "type": "python",
                   "request": "launch",
                   "module": "octoprint",
                   "args": [
                       "serve",
                       "--debug"
                   ],
                   "cwd": "${workspaceFolder}/src",
                   "preLaunchTask": "clean build artifacts"
               }
           ]
         }
```

2021-07-20 16:50 UTC, foosel approved these changes
Thumbs up from my side, not sure if @cp2004 still sees open points.

2021-07-20 16:53 UTC, cp2004 approved these changes

2021-07-20 16:56 UTC, merged

2021-07-20 17:12 UTC, Sycha commented
Adding black, flake8, isort to the devel dependencies seems to make sense to me, though having two different environments (pre-commit/devel) try and run the same task does introduce the risk of them diverging and giving inconsistent behaviour, so not the perfect solution.

I haven't been able to find a built in way to run the pre-commit on save so for now went with the vscode settings to run it from the built in formatter settings which happen to use the virtual environment.

This [extension](https://marketplace.visualstudio.com/items?itemName=jkillian.custom-local-formatters) suggests that adding new code formatters can only be done through an extension.

So currently either you get a consistent build environment by using an extension to use pre-commit for formatting but rely on ANOTHER vscode extension which could change at a moments notice or you get a virtual environment dependant formatter which could be a pain when working with legacy code and could be using different package versions to pre-commit.

Bit of a judgement call, but I am leaning towards a consistent use of pre-commit even though I dislike having another extension installed.

2021-07-29 09:45 UTC, thelastWallE commented
Nice addition for me as i use vsc!

There is also something i wanted to point out that is not related to this commit but is related to this instructions file. In the instructions on the first "half" of the instructions in environment.rst is like a copy of the second part where the instructions for windows and linux are separate.
I was using the first half to install octoprint in the venv, but after this i was reading the second part of the file and it was better to understand for me. I think the first part needs some cleaning of the things that are when again written in the second part.

I would do this myself, but i give the warning that i'm not a professional programmer and also not native english speaking.
Some last thing. If i would like to switch from python 2 to 3 and versa in vsc. Would i need to have like two setting.json files? Because of the ` "python.defaultInterpreterPath": "venv3/bin/python",`