Add Github Access Token clear checkbox
OctoPrint/OctoPrint pull request #4609
Opened 2022-08-04 17:35 UTC by FedericoNembrini

#### What does this PR do and why is it necessary?
Implementation of #4541
This PR adds the possibility of removing the Github Access Token once inserted.

#### How was it tested? How can it be tested by the reviewer?
Start OctoPrint, insert token, remove token.

#### Any background context you want to provide?

#### What are the relevant tickets if any?
#4541

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/25205086/182914217-71f893cd-9258-4a7e-a026-fa876c15e40f.png)

#### Further notes

2022-08-08 09:01 UTC, foosel requested changes
For the sake of consistency this should match the visuals of clearing an API key:

![image](https://user-images.githubusercontent.com/83657/183380199-2a2fdc82-fe95-4183-a82d-d5932e20caa9.png)

Implement it as an action button that triggers a settings save on the backend with the token set to undefined. That way you also don't need an additional observable just to track the state of a checkbox.

2022-09-07 14:24 UTC, foosel commented
FYI, seen the review request, it's on my TODO list, but I'm currently fully focused on 1.8.3.

2022-09-10 20:38 UTC, cp2004 requested changes
Looks good to me, just one fix for consistency with the naming.

2022-09-10 20:38 UTC, cp2004 commented on src/octoprint/plugins/softwareupdate/templates/snippets/githubToken.jinja2
> +            <a class="btn add-on btn-danger" title="Delete API Key" data-bind="click: function() { $root.deleteGithubTokenApiKey(); }, css: {'disabled': !$root.config_githubTokenSet()}"><i class="far
Just for consistency 👇 

```suggestion
            <a class="btn add-on btn-danger" title="Delete GitHub Access Token" data-bind="click: function() { $root.deleteGithubTokenApiKey(); }, css: {'disabled': !$root.config_githubTokenSet()}"><i class="far fa-trash-alt"></i></a>
```

2022-09-12 19:11 UTC, FedericoNembrini commented on src/octoprint/plugins/softwareupdate/templates/snippets/githubToken.jinja2
> +            <a class="btn add-on btn-danger" title="Delete API Key" data-bind="click: function() { $root.deleteGithubTokenApiKey(); }, css: {'disabled': !$root.config_githubTokenSet()}"><i class="far
Done 👍

2022-09-12 20:39 UTC, cp2004 approved these changes

2022-09-12 21:46 UTC, FedericoNembrini commented
I don't know if I need to re-request review from @foosel. Just to be sure, I will.

2022-09-28 12:51 UTC, merged

2022-09-28 12:52 UTC, foosel commented
Looking good now, thank you!