log extruder and file position on pause
OctoPrint/OctoPrint pull request #4820
Opened 2023-06-05 11:11 UTC by danielkucera

* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's `devel` branch if it's a completely
    new feature, or `maintenance` if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against `master` or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of `master`, `maintenance`, or `devel`
    please), e.g. `dev/my_new_feature` or `fix/my_bugfix`
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    `.less` source files, not the `.css` files (those are generated
    with `lessc`)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the `AUTHORS.md` file :)

#### What does this PR do and why is it necessary?
It logs extruder and file position to log in case of failure during pause state.

#### How was it tested? How can it be tested by the reviewer?
I run it during printing and the log showed added values

#### Any background context you want to provide?

#### What are the relevant tickets if any?

#### Screenshots (if appropriate)

#### Further notes

2023-06-05 15:32 UTC, foosel requested changes
First of all, I agree that getting that into the log makes sense 👍️

However, since the log line currently pretty much copies what's inside the event (minus the position), I wonder if it wouldn't make sense to extend the event here as well to include the file position (origin and file name are already there, your current code duplicates that information as it's also part of the `getFilePosition` response). 

And then we probably should also do the same for cancelling - not that much of interested in case of an issue during pausing, but rather very much helpful for people who want to attempt to rescue a print that got cancelled.

Event extension then also needs some docs.

Also, some small issues, see individual comments.

2023-06-05 15:32 UTC, foosel commented on src/octoprint/printer/standard.py
> +            fileposition = str(self._comm.getFilePosition())
`self._comm` might be `None` under certain (very unlikely but still possible) circumstances, so this needs a null-check.

2023-06-05 15:32 UTC, foosel commented on src/octoprint/printer/standard.py
> +                position = "unknown"
We can get rid of that and instead copy the fetch of `origin` etc below

2023-06-05 15:32 UTC, foosel commented on src/octoprint/printer/standard.py
> +                    position,
```suggestion
                    payload.get("position"),
```

2023-06-05 15:32 UTC, foosel commented
Also, as I just noticed, this should be filed against `maintenance`, not `devel`. It's an improvement of existing functionality, not a biiiiiig new feature that requires a ton of testing and lengthy integration processes first.

2023-06-06 08:59 UTC, danielkucera commented
@foosel , I've put everything into event data and included cancel event.

2023-06-19 08:41 UTC, danielkucera commented
It's updated, please check

2023-06-19 15:26 UTC, merged